<h1>Soal 1: Pemahaman</h1>

1. Sebutkan apa saja yang termasuk preprocessing data!
2. Jelaskan beberapa cara imputing missing value!
3. Kapan kita perlu melakukan feature centering dan scaling?
4. Bagaimana Data Science Workflow?

Jawab:
1. Preprocessing data yaitu melakukan feature engineering dimana bertujuan untuk mengubah data yang tidak bisa diolah menjadi dapat diproses, atau data yang kurang bagus menjadi layak, contohnya melakukan Encoding Categorical Data dan Imputing Missing Value.
2. - Drop data jika jumlah missing value banyak
   - Filling Mean/Median jika data missing bertipe numerik
   - Filling Modus jika data missing bertipe kategori
   - Filling dengan bfill atau ffill
   - KNN
3. Kita perlu melakukan feature centering dan scaling jika data fitur kita berada pada range yang berbeda jauh seperti ada yg puluhan, ratusan atau bahkan jutaan. Hal yang bisa dilakukan adalah melakukan Standarization, Normalization, Min-max Scaling data fitur.
4. - Data Source (Extract, Transform, Load)
   - Processing Data : EDA (Exploratory Data Analysis), Feature Engineering, Data Manipulation
   - Data Visualization
   - Data Modelling (using Machine Learning)
   - Deployment
   - Monitoring

---

<h1>Soal 2: Pengaplikasian</h1>

Selamat, sampai tahap ini kalian telah belajar banyak tentang data science, dari mulai python, data manipulasi, visualisasi, dan pembuatan model. Sekarang saatnya untuk mengaplikasikan semuanya.

Download dan gunakan data [titanic.csv](https://drive.google.com/uc?export=download&id=15-XQkmqj2UlFQH7rASJH1oxWST6o9mbm) sebagai data untuk pembuatan model ML. Pahami betul data ini dengan melakukan EDA (Explolatory Data Analaysis), Visualisasi, Data Analysis, Preprocessing Data, dan Modeling.

<b>(Optional)</b> Download dan gunakan data [titanic_test.csv](https://drive.google.com/uc?export=download&id=15-XQkmqj2UlFQH7rASJH1oxWST6o9mbm) untuk mengetest model kalian dengan melakukan prediksi terhadap data tersebut. Submit hasil prediksinya ke kaggle dan lihat scorenya. https://www.kaggle.com/c/titanic/submit

![alt text](https://drive.google.com/uc?id=1SyflO2YeuCdYhxwPF6CAtMeaNN1qTaFx)

In [1]:
# Code here
# Load Library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [39]:
titanic = pd.read_csv('titanic.csv')
titanic.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [40]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [4]:
titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [43]:
# Konversi Tipe Data
titanic[['Survived', 'Pclass']].astype('category')

    Survived Pclass
0          0      3
1          1      1
2          1      3
3          1      1
4          0      3
..       ...    ...
886        0      2
887        1      1
888        0      3
889        1      1
890        0      3

[891 rows x 2 columns]

In [42]:
titanic['Cabin'].mean()

KeyError: ignored